# Tomcat
server:
  port: 8085
spring:
  application:
    name: fisher-transaction-personal-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    virtual-host: /
    username: fisher
    password: fisher
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/fisher_personal_account?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  profiles:
    active: dev


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
